[package]
name = "xtra"
version = "0.1.0"
authors = ["Restioson <restiosondev@gmail.com>"]
edition = "2018"

[dependencies]
futures = { version = "^0.3" }
tokio = { version = "^0.2", features = ["rt-core", "time"], optional = true }
async-std = { version = "^1", features = ["unstable"], optional = true }

[features]
with-tokio-0_2 = ["tokio"]
with-async_std-1 = ["async-std"]

[[example]]
name = "basic_tokio"
path = "examples/basic_tokio.rs"
required-features = ["with-tokio-0_2", "tokio/full"]

[[example]]
name = "basic_tokio_async"
path = "examples/basic_tokio_async.rs"
required-features = ["with-tokio-0_2", "tokio/full"]

[[example]]
name = "crude_bench"
path = "examples/crude_bench.rs"
required-features = ["with-tokio-0_2", "tokio/full"]
