[package]
name = "xtra"
version = "0.1.0"
authors = ["Restioson <restiosondev@gmail.com>"]
edition = "2018"

[dependencies]
futures = { version = "^0.3" }
tokio = { version = "^0.2", features = ["rt-core"], optional = true }

[features]
default = ["tokio_spawn"]
tokio_spawn = ["tokio"]

[[example]]
name = "basic_tokio"
path = "examples/basic_tokio.rs"
required-features = ["tokio_spawn", "tokio/full"]