[package]
name = "xtra"
version = "0.5.0-beta.5"
description = "A tiny actor framework"
authors = ["Restioson <restiosondev@gmail.com>"]
edition = "2018"
license = "MPL-2.0"
repository = "https://github.com/Restioson/xtra"
documentation = "https://docs.rs/xtra"
readme = "README.md"
keywords = ["async", "actor", "futures", "xtra", "async-await"]
categories = ["asynchronous", "concurrency"]

[dependencies]
futures = { version = "0.3.5", default-features = false, features = ["alloc", "std"] }
async-trait = "0.1.36"
pollster = "0.2"

tokio = { version = "0.2", features = ["rt-core", "time"], optional = true }
smol = { version = "0.4", optional = true }
async-std = { version = "1", features = ["unstable"], optional = true}

# Wasm-bindgen support
wasm-bindgen = { version = "0.2", optional = true, default-features = false }
wasm-bindgen-futures = { version = "0.4", optional = true, default-features = false }
futures-timer = { version = "3", optional = true, default-features = false }

[dependencies.flume]
#git = "https://github.com/Restioson/flume/"
#branch = "async-edits"
path = "../flume"
default-features = false
features = ["async"]

[dev-dependencies]
smol = "0.4"
rand = "0.7"

[features]
default = []
with-tokio-0_2 = ["tokio"]
with-async_std-1 = ["async-std"]
with-wasm_bindgen-0_2 = ["wasm-bindgen", "wasm-bindgen-futures", "futures-timer/wasm-bindgen"]
with-smol-0_4 = ["smol"]

[[example]]
name = "basic_tokio"
path = "examples/basic_tokio.rs"
required-features = ["with-tokio-0_2", "tokio/full"]

[[example]]
name = "basic_async_std"
path = "examples/basic_async_std.rs"
required-features = ["with-async_std-1", "async-std/attributes"]

[[example]]
name = "basic_smol"
path = "examples/basic_smol.rs"
required-features = ["with-smol-0_4"]

[[example]]
name = "async_handler"
path = "examples/async_handler.rs"
required-features = ["with-tokio-0_2", "tokio/full"]

[[example]]
name = "interleaved_messages"
path = "examples/interleaved_messages.rs"
required-features = ["with-smol-0_4"]

[[example]]
name = "message_stealing"
path = "examples/message_stealing.rs"
required-features = ["with-smol-0_4"]

[[example]]
name = "crude_bench"
path = "examples/crude_bench.rs"
required-features = ["with-tokio-0_2", "tokio/full"]

[workspace]
members = ["examples/basic_wasm_bindgen"]
