[package]
name = "xtra"
version = "0.1.0"
authors = ["Restioson <restiosondev@gmail.com>"]
edition = "2018"

[dependencies]
crossbeam-channel = "^0.4"
tokio = { version = "^0.2", features = ["full"] }
